API-109-DDL-para-login-consentimento-de-usuarios
quarks-team/Projeto-Integrador-SPCGrafeno-BD pull request #6
Opened 2024-10-19 01:22 UTC by LeoAdlerr

2024-10-19 01:30 UTC, lucassbarcelos requested changes

2024-10-19 01:30 UTC, lucassbarcelos commented on DDLsConsentLgpd/MerUserPolicies.png
faltou o createdAt e Updatedat na user policies

2024-10-19 01:30 UTC, lucassbarcelos commented on DDLsConsentLgpd/consentUserTables.sql
> +    updated_at TIMESTAMP DEFAULT NOW() -- Timestamp when the user was last updated
add on update current_timestamp()

2024-10-19 01:30 UTC, lucassbarcelos commented on DDLsConsentLgpd/consentUserTables.sql
> +    updated_at TIMESTAMP DEFAULT NOW() -- Last updated timestamp
same

2024-10-22 22:21 UTC, DanielaMeirelles approved these changes

2024-10-23 23:48 UTC, lucassbarcelos approved these changes

2024-10-23 23:49 UTC, merged